#!/bin/bash

if (ps aux | grep Rose | grep -v grep > /dev/null) then
    echo RUNNING
else
    /Applications/Rose.app/Contents/MacOS/Rose &
fi

# common place to share files
mkdir -p /tmp/shared

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
export VAGRANT_CWD="$SCRIPT_DIR/src/vagrant"
vagrant up --no-provision
vagrant ssh win-11