#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
export VAGRANT_CWD="$SCRIPT_DIR/src/vagrant"
vagrant destroy --force win-11
# common place to share files
#mkdir -p /tmp/shared
vagrant up --no-provision #--no-destroy-on-error
vagrant provision win-11