---
- name: Playbook for windows 11
  hosts: all
  gather_facts: true
  become_method: runas
  become: yes
  become_user: vagrant

  tasks:
    - name: Disable UAC
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System'
        name: 'EnableLUA'
        data: 0
        type: dword

    - name: Disable IPv6
      ansible.windows.win_regedit:
        path: 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters'
        name: 'DisabledComponents'
        data: 0xFF
        type: dword

    - name: Disable firewall
      win_firewall:
        state: disabled

    - name: Disabling Local Administrator Password Expiration
      ansible.windows.win_user:
        name: Administrator
        password_never_expires: true

    - name: Disabling vagrant Password Expiration
      ansible.windows.win_user:
        name: vagrant
        password_never_expires: true

    - name: Install all updates and reboot as many times as needed
      ansible.windows.win_updates:
        category_names: '*'
        reboot: true
      
    - name: Ensure that WinRM services starts without delay
      ansible.windows.win_service:
        name: WinRM
        start_mode: auto

    - name: reclaim free disk space
      win_shell: "defrag.exe C: /H /L"