---
- name: Playbook for windows 11
  hosts: all
  gather_facts: true
  become_method: runas
  become: yes
  become_user: vagrant
  
  tasks:
    - name: Ensure Chocolatey is up-to-date
      win_chocolatey:
        name: chocolatey
        state: latest

    - name: install OpenSSH
      win_shell: Add-WindowsCapability -Online -Name OpenSSH.Server

    - name: Enable OpenSSH on startup
      win_shell: Set-Service -Name sshd -StartupType 'Automatic'

    - name: create .ssh folder for vagrant user
      win_shell: >
        if (!(Test-Path "$env:USERPROFILE\.ssh")) {
          New-Item -Path "$env:USERPROFILE\.ssh" -ItemType Directory
        }

    - name: install vagrant public key to vagrant user
      win_shell: |
        $pubkey_url = "https://raw.githubusercontent.com/hashicorp/vagrant/main/keys/vagrant.pub"
        Invoke-WebRequest -Uri $pubkey_url -OutFile "$env:USERPROFILE\.ssh\authorized_keys" -UseBasicParsing

    - name: install vagrant public key to Administrator user
      win_shell: cp "$env:USERPROFILE\.ssh\authorized_keys" "$env:ProgramData\ssh\administrators_authorized_keys"

    - name: Start OpenSSH
      win_shell: Start-Service sshd

    - name: Set the default shell to PowerShell
      win_shell: >
        New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value
        "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"
        -PropertyType String -Force

    - name: Ensure RDP service is running and enabled
      win_service:
        name: TermService
        start_mode: auto
        state: started

    - name: Set the registry key to enable RDP
      ansible.windows.win_regedit:
        path: HKLM:\System\CurrentControlSet\Control\Terminal Server
        name: fDenyTSConnections
        type: dword
        data: 0

    - name: Install git
      win_chocolatey:
        name: git
        state: present

    - name: Install firefox
      win_chocolatey:
        name: firefox
        state: present

    - name: disable auto logon counter
      ansible.windows.win_regedit:
        path: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
        name: 'AutoLogonCount'
        data: 0
        type: dword

    - name: make windows automatically logon
      ansible.windows.win_regedit:
        path: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
        name: 'AutoAdminLogon'
        data: 1
        type: string

    - name: set auto logon username
      ansible.windows.win_regedit:
        path: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
        name: 'DefaultUserName'
        data: 'vagrant'
        type: string

    - name: set auto logon password
      ansible.windows.win_regedit:
        path: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
        name: 'DefaultPassword'
        data: 'vagrant'
        type: string

# install nmap manually

    # - name: Install VS Tools
    #   win_chocolatey:
    #     name: visualstudio2022buildtools
    #     state: present
    #     version: '117.9.0.0'
    #     package_params:
    #       "--includeOptional --add Microsoft.VisualStudio.Workload.NodeBuildTools --add Microsoft.VisualStudio.Workload.WebBuildTools --add Microsoft.VisualStudio.Workload.DataBuildTools --add Microsoft.VisualStudio.Workload.MSBuildTools"
    #   register: vs_output



# echo "install choco"
# [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

# # Create a powershell profile
# New-Item -path $PROFILE -type file -force
# Add-Content -Path $PROFILE -Value "`$env:Path += ';C:\ProgramData\chocolatey\bin'"

# echo "install dev tools"
# choco install -y git
# Add-Content -Path $PROFILE -Value "`$env:Path += ';C:\Program Files\Git\bin'"
# choco install -y netcat
# choco install -y visualstudio2022buildtools
# Add-Content -Path $PROFILE -Value "`$env:Path += ';C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin'"
# choco install -y firefox
# #choco install -y openvpn #doesn't work
# Add-Content -Path $PROFILE -Value "`$env:Path += ';C:\Program Files\OpenVPN\bin'"
# #ROSE
# #cd ~/Desktop
# #reload terminal
# #git clone https://github.com/BlueSquid1/rose.git
# #cd rose
# #& 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe' modify --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools" --config ".\client\rose.vsconfig" --quiet
# #Add-Content -Path $PROFILE -Value "`$env:Path += ';C:\Program Files\dotnet'"
# #cd client
# #reload terminal
# #dotnet restore
# #MSBuild.exe /property:Configuration=Release
# #cp -r .\rose\bin\Release\net8.0 'C:\Program Files\Rose'
# #Add-Content -Path $PROFILE -Value "`$env:Path += ';C:\Program Files\Rose'"
# #reload terminal
# #open regedit and set SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\fAllowUnlistedRemotePrograms to 1