# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = File.read(__dir__ + "/src/rebuild.ps1")

Vagrant.configure("2") do |config|
  config.vm.define "win-11"
  config.vm.box = "hbsmith/win11-arm"
  config.vm.boot_timeout = 60
  #config.vm.communicator = "winrm"
  config.vm.guest = :windows
  config.vm.communicator = "ssh"
  
  #config.vm.network "private_network", type: "dhcp" #only added to avoid a bug with vagrant/parallels were the default network can't communicate with the host

  config.vm.synced_folder "/tmp/shared", "C:\\windows\\Temp\\shared", create: true

  config.vm.provision "shell", inline: $script  
end
