# -*- mode: ruby -*-
# vi: set ft=ruby :

current_script_path = File.dirname(File.expand_path(__FILE__))

Vagrant.configure("2") do |config|
  config.vm.define 'win-11'
  config.vm.box = '/Users/clintonpage/Desktop/mygit/win-parallels/box/Windows_11_ARM64.box'

  config.vm.provider "parallels" do |prl|
    prl.memory = 8192
    prl.cpus = 4
  end
  

  config.vm.guest = :windows
  config.vm.communicator = "winrm"

  config.vm.synced_folder "~/shared", 'C:\Users\vagrant\shared', create: true

  # There is a bug when using ansible via winrm where it can't find the ip address of the guest.
  # workaround is to retrieve the ip address via the script below before calling the ansible playbook.  
  config.vm.provision :host_shell do |host_shell|
    $script = <<-'SCRIPT'
      guest_ip=$(vagrant winrm-config win-11 | awk '/HostName/ { print $2; exit }')
      echo  "win-11 ansible_host=$guest_ip" > ./inventory.ini
      while ! [ -s ./inventory.ini ]; do
        sleep 1
      done
    SCRIPT
    host_shell.inline = $script
  end

  config.vm.provision "ansible" do |ansible|
    ansible.inventory_path = "#{current_script_path}/inventory.ini"
    ansible.extra_vars = {
      ansible_connection: 'winrm',
      ansible_user: 'vagrant',
      ansible_password: 'vagrant',
      ansible_port: 5985
    }
    ansible.playbook = "#{current_script_path}/playbook.yml"
  end
end
